Shopping = new Meteor.Collection ("shopping");
Fridge = new Meteor.Collection("fridge");
Meals = new Meteor.Collection("meals");//new
Favorites = new Meteor.Collection("favorites");//your favorite recipes
Friends = new Meteor.Collection("friends");//favorite recipes of friends
Rec = new Meteor.Collection("rec"); //traversing through the array
Ins = new Meteor.Collection("ins");//instructions
Hello = new Meteor.Collection("hello");
He = new Meteor.Collection("he");
