Shopping = new Meteor.Collection ("shopping");
Fridge = new Meteor.Collection("fridge");
Meals = new Meteor.Collection("meals");//new
Favorites = new Meteor.Collection("favorites");//your favorite recipes
Friends = new Meteor.Collection("friends");//favorite recipes of friends
Ins = new Meteor.Collection("ins"); //instructions for recipes
Rec = new Meteor.Collection("rec"); //recipes
Health = new Meteor.Collection("health"); //health parameters for recipes
Today = new Meteor.Collection("today");
Weekly = new Meteor.Collection("weekly");
Monthly = new Meteor.Collection("monthly");